version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 7.0.0
  build:
    commands:
      - node --version
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/*
    - images/*